### ISSUE TITLE
Speed diff between DynamicCacheSplitHeadFlatten and DynamicCacheSplitHead?

### ISSUE THREAD

**Issue by GeneZC** [FFY0/AdaKV#2]
Will DynamicCacheSplitHeadFlatten be much faster than DynamicCacheSplitHead?

**Comment by FFY0** [comment]
Yes. This improvement is primarily due to the cache flatten layout and the customized CUDA kernel utilized in DynamicCacheSplitHeadFlatten, which enable the fusion and parallelization of variable-length cache update operations across multiple heads. This enhances GPU utilization and reduces latency, achieving computational efficiency comparable to vanilla flash attention based on conventional cache layout, as detailed in our paper's appendix A.2. Additionally, the cache flatten layout better supports the flash_attn_varlen_func, eliminating unnecessary transformations for subsequent computations. For those seeking a simpler way to validate and refine the idea of variable-length budget allocation, we also provide the DynamicCacheSplitHead implementation, which, although slower, is easier to understand.

**Comment by GeneZC** [comment]
I see, thanks~
